//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaykonIntegrationApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaykonIntegrationApp.Resources.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box number.
        /// </summary>
        public static string BoxNumber {
            get {
                return ResourceManager.GetString("BoxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of cone:.
        /// </summary>
        public static string Colorofconus {
            get {
                return ResourceManager.GetString("Colorofconus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of cone.
        /// </summary>
        public static string Colorofconus2 {
            get {
                return ResourceManager.GetString("Colorofconus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cone color.
        /// </summary>
        public static string Conecolor {
            get {
                return ResourceManager.GetString("Conecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select COM port.
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error scale is not stable.
        /// </summary>
        public static string ErrorScale {
            get {
                return ResourceManager.GetString("ErrorScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross weight.
        /// </summary>
        public static string Grossweight {
            get {
                return ResourceManager.GetString("Grossweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot:.
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Lot2 {
            get {
                return ResourceManager.GetString("Lot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean weight.
        /// </summary>
        public static string MeanWeight {
            get {
                return ResourceManager.GetString("MeanWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netto weight.
        /// </summary>
        public static string Nettoweight {
            get {
                return ResourceManager.GetString("Nettoweight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature:.
        /// </summary>
        public static string Nomenklatura {
            get {
                return ResourceManager.GetString("Nomenklatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclature.
        /// </summary>
        public static string Nomenklatura2 {
            get {
                return ResourceManager.GetString("Nomenklatura2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of box.
        /// </summary>
        public static string NumberofBox {
            get {
                return ResourceManager.GetString("NumberofBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of first box:.
        /// </summary>
        public static string Numberoffirstbox {
            get {
                return ResourceManager.GetString("Numberoffirstbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok and print.
        /// </summary>
        public static string OkWithPrint {
            get {
                return ResourceManager.GetString("OkWithPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date.
        /// </summary>
        public static string Productiondate {
            get {
                return ResourceManager.GetString("Productiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change:.
        /// </summary>
        public static string Smena {
            get {
                return ResourceManager.GetString("Smena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Smena2 {
            get {
                return ResourceManager.GetString("Smena2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baykon intagration application. FRE.
        /// </summary>
        public static string TitleNameMainWindow {
            get {
                return ResourceManager.GetString("TitleNameMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View of box:.
        /// </summary>
        public static string ViewOfBox {
            get {
                return ResourceManager.GetString("ViewOfBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View of box.
        /// </summary>
        public static string ViewOfBox2 {
            get {
                return ResourceManager.GetString("ViewOfBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View of packaging.
        /// </summary>
        public static string Viewofpackaging {
            get {
                return ResourceManager.GetString("Viewofpackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight box.
        /// </summary>
        public static string WeightBox {
            get {
                return ResourceManager.GetString("WeightBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight brutto.
        /// </summary>
        public static string WeightBrutto {
            get {
                return ResourceManager.GetString("WeightBrutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight neto.
        /// </summary>
        public static string WeightNeto {
            get {
                return ResourceManager.GetString("WeightNeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wieght of box:.
        /// </summary>
        public static string Weightofbox {
            get {
                return ResourceManager.GetString("Weightofbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wieght of box.
        /// </summary>
        public static string Weightofbox2 {
            get {
                return ResourceManager.GetString("Weightofbox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight of packing.
        /// </summary>
        public static string Weightofpacking {
            get {
                return ResourceManager.GetString("Weightofpacking", resourceCulture);
            }
        }
    }
}
